// ---------- ITEMS
const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
// ---------- Create ITEMS
const ITEMS_POST_DATA_SUCCESS = 'ITEMS_POST_DATA_SUCCESS';
const ITEMS_POST_DATA_HAS_ERRORED = 'ITEMS_POST_DATA_HAS_ERRORED';
const ITEMS_POST_DATA_IS_LOADING = 'ITEMS_POST_DATA_IS_LOADING';

export default {
	ITEMS_IS_LOADING,
	ITEMS_HAS_ERRORED,
	ITEMS_FETCH_DATA_SUCCESS,
	ITEMS_POST_DATA_SUCCESS,
	ITEMS_POST_DATA_HAS_ERRORED,
	ITEMS_POST_DATA_IS_LOADING,
};